### ISSUE TITLE
Auto-post to Twitter

### ISSUE THREAD

**Issue by maxvoltar** [maxvoltar/photo-stream#11]
Can we post newly added photos to Twitter automatically?

**Comment by tommoor** [comment]
You have RSS...

RSS -> IFTTT/Zapier -> Twitter 😄

**Comment by maxvoltar** [comment]
How do we display the actual photo on Twitter? See https://github.com/maxvoltar/maxvoltar-photo/issues/9 as to why this is a bit tricky (tl;dr: Photos don't have a unique page, just a URL).

**Comment by maxvoltar** [comment]
I think the best way to do this is to embed the `/large` photo in a tweet at add its URL too.

**Comment by maxvoltar** [comment]
Update: IFTTT has an “post image in tweet” applet that’ll pull the article image defined in the feed, so this works. Gotta keep an eye on whether it keeps working with all the changes we’re making to with photo pages.
