### ISSUE TITLE
Optimize build time

### ISSUE THREAD

**Issue by maxvoltar** [maxvoltar/photo-stream#20]
Only process images that don’t have thumbnails yet.

**Comment by maxvoltar** [comment]
We’re burning through build time ATM 😂

**Comment by maxvoltar** [comment]
@benubois looked at the `image-processing` documentation but couldn’t find anything to disable generation for already resized images.

**Comment by benubois** [comment]
Just pushed an update today which caches the resized images. 

Running this to get the latest version:

`bundle update jekyll_image_processing`

However, this only helps when running locally. Are you asking about Netlify build time? They have a way to share a cache between builds that I could look into.

**Comment by maxvoltar** [comment]
Not super worried about Netlify if it’s too much work. Thanks for the local build stuff!
