### ISSUE TITLE
If VIPS throws an error, the thumbnail is generated but the HTML is skipped

### ISSUE THREAD

**Issue by cloudz** [maxvoltar/photo-stream#49]
Pictures from my Nikon D850 error out. They throw this error: 

```bad exif meta "exif-ifd3-GPSVersionID"```

This results in the image being resized, tinted, thumbnailed but the HTML not generated.

**Comment by maxvoltar** [comment]
Just checking: This didn't actually block the HTML from getting generated, right?

**Comment by cloudz** [comment]
The first time it did - but there was also a rights issue from the pictures from Photos dragged into the originals folder. I'm running everything locally & sync the _site folder to a static webserver.
