### ISSUE TITLE
docker support?

### ISSUE THREAD

**Issue by esrrhs** [maxvoltar/photo-stream#53]

**Comment by maxvoltar** [comment]
Done, thanks to @brianmcarey 🙂

**Comment by esrrhs** [comment]
@maxvoltar great, and maybe you can upload the official image to docker hub?

**Comment by maxvoltar** [comment]
@esrrhs how and where would I do that?

**Comment by esrrhs** [comment]
@maxvoltar 
1. Create your account in https://hub.docker.com
2. Click create Repository, and connected to github, then you can see your repository in github
3. Choose the photo-steam, and click BUILD RULES
done, it will auto build an image when your repository changed. and then we can pull the latest image from dockerhub.

**Comment by rc1** [comment]
Hey @esrrhs, nice one for making the Dockerfile. 

Running the dockerfile doing "4000:4000" didn't work for me as http://localhost:4000/ on my host wouldn't resolve. I fixed this by changing the entry point to:

`ENTRYPOINT bundle exec jekyll serve --host 0.0.0.0`

Should this be the entry point or am I doing something wrong. I've used docker a bit, but this is the first time I've used Docker for Windows so it could be that.

**Comment by esrrhs** [comment]
@rc1 oh, you ask the wrong guy, the Dockerfile is writed by  @brianmcarey ,  he can answer your questions

**Comment by brianmcarey** [comment]
There are a few quirks with Docker for Windows from what I've heard.  

Both entrypoints work on Linux hosts so you can create a PR if you want to make the update for Windows hosts.

**Comment by LucaDanelutti** [comment]
On a raspberry pi with raspbian installed I had to change the entry point to:

`ENTRYPOINT bundle exec jekyll serve --host 0.0.0.0`

otherwise it won't load. Thanks @rc1!
