### ISSUE TITLE
Feature Request: Individual Photo Metadata

### ISSUE THREAD

**Issue by sebj** [maxvoltar/photo-stream#58]
It'd be useful to have the option to show photo EXIF metadata on individual photo pages. In particular, I'd love to see GPS location data pulled out and shown with a small labelled map preview ([Apple MapKit JS](https://developer.apple.com/maps/web/) w/ the static image 'Snapshots' feature listed near the bottom?).

Perhaps this could be hidden until an (i) icon is pressed?

**Comment by maxvoltar** [comment]
We're using EXIF data to order the photos by date taken. If you go look at the photos page, you can see that there's more data there (camera, aperture, shutter), it's just commented out because I couldn't figure out a proper design. Feel free to take a stab at it 🙂
