### ISSUE TITLE
The preview image doesn't show up for Photo pages.

### ISSUE THREAD

**Issue by lucky13820** [maxvoltar/photo-stream#61]
![CleanShot 2020-03-16 at 16 41 24](https://user-images.githubusercontent.com/7293811/76808437-063ac100-67a5-11ea-952b-39c59ed7808a.jpg)

All the preview images tag only have the site URL, not the image link.

**Comment by maxvoltar** [comment]
@lucky13820 mind sharing the `/` path you were looking at? The correct preview image gets set in the header when you navigate to it from the URL bar in your browser, not immediately after clicking the image.

**Comment by lucky13820** [comment]
Pretty much all the image links. Both on your site and my own site.
https://ryanyao.photos/fog-grass https://maxvoltar.photo/last-christmas-location Twitter title is set correctly, but not the preview image.

**Comment by lukekarrys** [comment]
I might've tracked this down in #73. Curious if it works for you @lucky13820?

**Comment by lucky13820** [comment]
Yeah, it works perfectly. Although, I think the correct meta name for Twitter image is `twitter:image`.
