### ISSUE TITLE
Alphabetical and random organization

### ISSUE THREAD

**Issue by camilokoch** [maxvoltar/photo-stream#68]
i understand that photos are ordered by exif data, but i need to order them alphabetically and randomly. is it possible? what part of the code should i modify? thank you for creating photo-stream, tim

**Comment by daehn** [comment]
I think having a look at https://github.com/maxvoltar/photo-stream/blob/master/_plugins/photo_filter.rb is a good idea. It looks like that's were the current sorting based on the EXIF date happens.

**Comment by maxvoltar** [comment]
What @daehn said 🙂 There are no plans to offer any other sorting options for now, but it shouldn't be too hard to make the changes yourself.
