### ISSUE TITLE
can't deploy on netlify anymore

### ISSUE THREAD

**Issue by camilokoch** [maxvoltar/photo-stream#80]
1:34:50 PM: ┌─────────────────────────────┐
1:34:50 PM:  │   "build.command" failed                                                                     │
1:34:50 PM: └─────────────────────────────┘
1:34:50 PM: ​
1:34:50 PM:   Error message
1:34:50 PM:   Command failed with exit code 1: jekyll build
1:34:50 PM: ​
1:34:50 PM:   Error location
1:34:50 PM:   In Build command from Netlify app:
1:34:50 PM:   jekyll build

any advice?

**Comment by camilokoch** [comment]
syntax error from my side, apologies

**Comment by adityag81** [comment]
I'm getting the same error. It was deploying fine, and now suddenly it won't deploy on Netflify. What did you do to rectify this? 

> syntax error from my side, apologies

**Comment by camilokoch** [comment]
hello, @adityag81, i had an extra space in _config.yml: `author: `; i corrected that syntax error to `author:` and my issue was gone. best
